<a href="https://colab.research.google.com/github/nehaverma13/python-for-data-science/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Numpy


In [33]:
import numpy as np

In [34]:
myarrr = np.array([2,3,48,52])

In [35]:
myarrr

array([ 2,  3, 48, 52])

In [36]:
myarr = np.array([2,3,4,2]),np.int8

##Array creation -
####Conversion from other python structure

In [41]:
listarray = np.array([[1,2,3],[5,6,7],[8,9,5]])

In [39]:
listarray.shape

(3, 3)

In [40]:
listarray.size

9

In [42]:
listarray.dtype

dtype('int64')

In [44]:
np.array ({34,2,2})

array({34, 2}, dtype=object)

In [45]:
zeros= np.zeros ((2,4))

In [46]:
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [47]:
zeros= np.zeros((4,5))

In [48]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [52]:
rng= np.arange(20)

In [53]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [54]:
lspace = np.linspace(1,5,10)

In [55]:
lspace

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [56]:
emp= np.empty((2,3))

In [57]:
emp

array([[3.39487683e-316, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])

In [58]:
emp_like =np.empty_like((1,2))

In [59]:
emp_like

array([36977072,        2])

In [60]:
emp_like =np.empty_like((3,2))

In [61]:
emp_like

array([  36977056, 4294967296])

In [62]:
emp_like =np.empty_like(lspace)

In [63]:
emp_like

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [66]:
ide= np.identity(10)

In [67]:
ide

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [68]:
ide.shape

(10, 10)

In [69]:
ide.size

100

In [70]:
arr=np.arange(99)

In [71]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [74]:
arr=np.arange(201)

In [75]:
arr

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [76]:
x=[[1,2,3],[4,5,6],[7,8,9]]

In [77]:
ar= np.array(x)

In [78]:
ar.sum(axis=0)

array([12, 15, 18])

In [80]:
ar.sum(axis=1)

array([ 6, 15, 24])

In [81]:
ar.size

9

In [82]:
ar.shape

(3, 3)

In [83]:
ar.dtype

dtype('int64')

In [84]:
ar.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [86]:
ar.ndim

2

In [87]:
ar.flat

In [90]:
for item in ar.flat:
  print(item)

1
2
3
4
5
6
7
8
9


In [94]:
ar.nbytes

72

In [96]:
one=np.array([2,4,1,32,31,3])

In [97]:
one.argmax()

3

In [98]:
one.argmin()

2

In [99]:
one.argsort()

array([2, 0, 5, 1, 4, 3])

In [100]:
ar.argmax(axis=0)

array([2, 2, 2])

In [101]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [102]:
ar.argmax(axis=1)

array([2, 2, 2])

In [103]:
ar.reshape(9,1)


array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [104]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [105]:
ar2= np.array([[1,2,1],[2,3,4],[3,2,1]])

In [106]:
ar + ar2

array([[ 2,  4,  4],
       [ 6,  8, 10],
       [10, 10, 10]])

In [107]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [108]:
ar2

array([[1, 2, 1],
       [2, 3, 4],
       [3, 2, 1]])

In [109]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [110]:
np.where(ar>4)

(array([1, 1, 2, 2, 2]), array([1, 2, 0, 1, 2]))

In [111]:
type(np.where(ar>4))

tuple

In [113]:
np.count_nonzero(ar)

9